/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author nathi
 */
public class TelaDenuncia extends javax.swing.JFrame {

    /**
     * Creates new form TelaDenuncia
     */
    public TelaDenuncia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDenuncie = new javax.swing.JPanel();
        cabecalho = new javax.swing.JLabel();
        descrevaInfracao = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        painelDescrevaInfracao = new javax.swing.JTextPane();
        botaoVoltar = new javax.swing.JButton();
        rua = new javax.swing.JLabel();
        textoRua = new javax.swing.JTextField();
        botaoEnviar = new javax.swing.JButton();
        cep = new javax.swing.JLabel();
        textoCep = new javax.swing.JTextField();
        numero = new javax.swing.JLabel();
        textoNumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Denúncia");

        painelDenuncie.setBackground(new java.awt.Color(255, 255, 255));

        cabecalho.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cabecalho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cabecalho.setText("Denuncie aqui:");
        cabecalho.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        descrevaInfracao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        descrevaInfracao.setText("Descreva a infração:");

        scroll.setViewportView(painelDescrevaInfracao);

        botaoVoltar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        botaoVoltar.setText("Voltar");

        rua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rua.setText("Rua:");

        textoRua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        botaoEnviar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        botaoEnviar.setText("Enviar");

        cep.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cep.setText("Cep:");

        textoCep.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        numero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        numero.setText("Nº:");

        textoNumero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout painelDenuncieLayout = new javax.swing.GroupLayout(painelDenuncie);
        painelDenuncie.setLayout(painelDenuncieLayout);
        painelDenuncieLayout.setHorizontalGroup(
            painelDenuncieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDenuncieLayout.createSequentialGroup()
                .addGroup(painelDenuncieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDenuncieLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDenuncieLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoVoltar))
                    .addGroup(painelDenuncieLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(painelDenuncieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descrevaInfracao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDenuncieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDenuncieLayout.createSequentialGroup()
                                    .addGroup(painelDenuncieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rua)
                                        .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(painelDenuncieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoCep, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(painelDenuncieLayout.createSequentialGroup()
                                            .addComponent(textoRua, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(scroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 161, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(painelDenuncieLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(botaoEnviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelDenuncieLayout.setVerticalGroup(
            painelDenuncieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDenuncieLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoVoltar)
                .addGap(85, 85, 85)
                .addComponent(descrevaInfracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDenuncieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rua)
                    .addComponent(textoRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero)
                    .addComponent(textoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDenuncieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cep)
                    .addComponent(textoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(botaoEnviar)
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelDenuncie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelDenuncie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDenuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDenuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDenuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDenuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDenuncia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel cabecalho;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel descrevaInfracao;
    private javax.swing.JLabel numero;
    private javax.swing.JPanel painelDenuncie;
    private javax.swing.JTextPane painelDescrevaInfracao;
    private javax.swing.JLabel rua;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField textoCep;
    private javax.swing.JTextField textoNumero;
    private javax.swing.JTextField textoRua;
    // End of variables declaration//GEN-END:variables
}
